version: "3.3"
services:
  covidtest:
    container_name: covidtest.cmru.ac.th
    ports:
      - "3002:3000"
    volumes:
      - "/usr/src/app"
    restart: always
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=production
      - PRINT_SERVER=localhost
      - PRINT_SERVER_PORT=3001
    build:
      context: .
      dockerfile: Dockerfile
